// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtsG3FOmGhCE0rK4ygqr_mwxTlR06T50Q',
    appId: '1:1003878887727:android:a03a836a876d5217ea31da',
    messagingSenderId: '1003878887727',
    projectId: 'vakloe-8bc04',
    storageBucket: 'vakloe-8bc04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6SlQVYCOsDkCbgMBGJOM8wZNmancs5I0',
    appId: '1:1003878887727:ios:a5fc35b3740b1df4ea31da',
    messagingSenderId: '1003878887727',
    projectId: 'vakloe-8bc04',
    storageBucket: 'vakloe-8bc04.appspot.com',
    androidClientId: '1003878887727-pg3pg1knaj4rsen073kmr1pkj45fa6t6.apps.googleusercontent.com',
    iosClientId: '1003878887727-4ian5kroep296out0uomsl5rm182og24.apps.googleusercontent.com',
    iosBundleId: 'com.example.lavauto',
  );
}
